-- V1.1.12 follow-up: normalize constraint name generated by identifier truncation

ALTER TABLE public.mo_workflow_recommendation_package_nodes
    DROP CONSTRAINT IF EXISTS ck_mo_workflow_recommendation_package_nodes_parent_requires_pac;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_mo_wf_pkg_nodes_parent_requires_pkg'
    ) THEN
        ALTER TABLE public.mo_workflow_recommendation_package_nodes
            ADD CONSTRAINT ck_mo_wf_pkg_nodes_parent_requires_pkg
            CHECK (
                parent_package_node_id IS NULL
                OR package_id IS NOT NULL
            );
    END IF;
END $$;
